services:

  - type: web
    name: ai-stress-test-lab

    env: python

    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: GEMINI_API_KEY
        sync: false